"""
Template Pools - 20-50 replacement templates per domain for structured variation.
Templates use {placeholders} that get filled with specific data.
"""
from typing import Dict, List

TEMPLATE_POOLS: Dict[str, Dict[str, List[str]]] = {
    "legal": {
        # ACCOUNT DISPUTE TEMPLATES (50 variations)
        "account_dispute": [
            "The account identified as {account_number} with {creditor_name} is being disputed as {dispute_reason}",
            "I formally dispute account {account_number} from {creditor_name} on the grounds that it is {dispute_reason}",
            "Account number {account_number} reported by {creditor_name} is {dispute_reason} and must be corrected",
            "The entry for {creditor_name} (account {account_number}) is {dispute_reason}",
            "I am disputing {creditor_name} account {account_number} because it is {dispute_reason}",
            "The account bearing number {account_number} from {creditor_name} appears as {dispute_reason}",
            "Account {account_number} ({creditor_name}) is reported {dispute_reason} in violation of accuracy requirements",
            "The {creditor_name} account numbered {account_number} contains {dispute_reason} information",
            "I challenge account {account_number} from {creditor_name} as being {dispute_reason}",
            "The reported account {account_number} with {creditor_name} is {dispute_reason}",
            "Account number {account_number}, reported by {creditor_name}, is {dispute_reason}",
            "I hereby dispute the {creditor_name} account ({account_number}) which is {dispute_reason}",
            "The account from {creditor_name} bearing number {account_number} is {dispute_reason}",
            "Account {account_number} as reported by {creditor_name} is {dispute_reason}",
            "I contest account {account_number} ({creditor_name}) on grounds of being {dispute_reason}",
            "The {creditor_name} entry for account {account_number} is {dispute_reason}",
            "Account number {account_number} from {creditor_name} is disputed as {dispute_reason}",
            "I am formally challenging {creditor_name} account {account_number} for being {dispute_reason}",
            "The account {account_number} reported under {creditor_name} is {dispute_reason}",
            "Account {account_number} with {creditor_name} appears incorrectly as {dispute_reason}",
            "I dispute the {creditor_name} account identified by number {account_number} as {dispute_reason}",
            "The reported entry for {creditor_name} ({account_number}) is {dispute_reason}",
            "Account number {account_number} attributed to {creditor_name} is {dispute_reason}",
            "I challenge the accuracy of {creditor_name} account {account_number} which is {dispute_reason}",
            "The {creditor_name} account with number {account_number} is reported as {dispute_reason}",
            "Account {account_number} from the creditor {creditor_name} is {dispute_reason}",
            "I formally contest account {account_number} under {creditor_name} as {dispute_reason}",
            "The entry for account {account_number} ({creditor_name}) is {dispute_reason}",
            "Account number {account_number} listed under {creditor_name} is {dispute_reason}",
            "I am disputing the accuracy of {creditor_name} account {account_number}: {dispute_reason}",
            "The account numbered {account_number} from {creditor_name} shows {dispute_reason} data",
            "Account {account_number} as listed by {creditor_name} is {dispute_reason}",
            "I contest the {creditor_name} entry bearing account number {account_number} as {dispute_reason}",
            "The reported account from {creditor_name} ({account_number}) is {dispute_reason}",
            "Account number {account_number} under creditor {creditor_name} is {dispute_reason}",
            "I hereby challenge account {account_number} from {creditor_name}: {dispute_reason}",
            "The {creditor_name} account (number {account_number}) contains {dispute_reason} information",
            "Account {account_number} attributed to {creditor_name} is disputed for being {dispute_reason}",
            "I formally dispute the entry for {creditor_name} account {account_number} as {dispute_reason}",
            "The account identified as {account_number} under {creditor_name} is {dispute_reason}",
            "Account number {account_number} reported by the creditor {creditor_name} is {dispute_reason}",
            "I am challenging {creditor_name}'s account {account_number} on the basis that it is {dispute_reason}",
            "The reported {creditor_name} account ({account_number}) appears as {dispute_reason}",
            "Account {account_number} from creditor {creditor_name} is being disputed: {dispute_reason}",
            "I contest the accuracy of account {account_number} ({creditor_name}) which is {dispute_reason}",
            "The {creditor_name} entry for account number {account_number} shows {dispute_reason}",
            "Account number {account_number} with creditor {creditor_name} is disputed as being {dispute_reason}",
            "I hereby dispute {creditor_name} account numbered {account_number}: {dispute_reason}",
            "The account from creditor {creditor_name} (#{account_number}) is {dispute_reason}",
            "Account {account_number} listed by {creditor_name} contains {dispute_reason} information",
        ],

        # BALANCE DISPUTE TEMPLATES (40 variations)
        "balance_dispute": [
            "The reported balance of {reported_balance} is incorrect; the actual balance is {actual_balance}",
            "I dispute the balance shown as {reported_balance} which should be {actual_balance}",
            "The balance of {reported_balance} is inaccurate and should reflect {actual_balance}",
            "The stated balance ({reported_balance}) is wrong; correct balance is {actual_balance}",
            "I challenge the reported balance of {reported_balance}; it should be {actual_balance}",
            "The balance is incorrectly shown as {reported_balance} when it should be {actual_balance}",
            "I dispute that the balance is {reported_balance}; the accurate figure is {actual_balance}",
            "The reported figure of {reported_balance} is erroneous; actual balance: {actual_balance}",
            "The balance showing {reported_balance} is inaccurate; should show {actual_balance}",
            "I contest the balance of {reported_balance} as incorrect; true balance is {actual_balance}",
            "The account balance of {reported_balance} does not match the correct amount of {actual_balance}",
            "I dispute the {reported_balance} balance; records show {actual_balance}",
            "The reported balance ({reported_balance}) is false; correct amount is {actual_balance}",
            "I challenge the stated balance of {reported_balance} which should read {actual_balance}",
            "The balance is erroneously reported as {reported_balance}; it should be {actual_balance}",
            "I dispute that the account shows {reported_balance}; the balance is {actual_balance}",
            "The incorrect balance of {reported_balance} should be corrected to {actual_balance}",
            "I contest the {reported_balance} figure; accurate balance is {actual_balance}",
            "The balance shown as {reported_balance} is disputed; correct figure: {actual_balance}",
            "I challenge the inaccurate balance of {reported_balance}; should be {actual_balance}",
            "The erroneous balance of {reported_balance} must be corrected to {actual_balance}",
            "I dispute the reported {reported_balance} balance as inaccurate; actual: {actual_balance}",
            "The false balance of {reported_balance} should reflect the true balance of {actual_balance}",
            "I contest that the balance is {reported_balance}; correct amount is {actual_balance}",
            "The stated {reported_balance} balance is wrong and should be {actual_balance}",
            "I challenge the balance entry of {reported_balance}; accurate amount is {actual_balance}",
            "The balance figure of {reported_balance} is incorrect; it should read {actual_balance}",
            "I dispute the inaccurate {reported_balance} balance; true figure is {actual_balance}",
            "The reported amount of {reported_balance} should be corrected to {actual_balance}",
            "I contest the erroneous {reported_balance} figure; actual balance: {actual_balance}",
            "The balance incorrectly shows {reported_balance} instead of {actual_balance}",
            "I dispute the {reported_balance} reported balance; it should state {actual_balance}",
            "The false {reported_balance} balance must be changed to {actual_balance}",
            "I challenge that the balance reads {reported_balance}; correct figure is {actual_balance}",
            "The balance of {reported_balance} is disputed as incorrect; should be {actual_balance}",
            "I contest the stated {reported_balance}; the accurate balance is {actual_balance}",
            "The erroneous {reported_balance} figure should reflect {actual_balance}",
            "I dispute this balance: reported {reported_balance}, actual {actual_balance}",
            "The {reported_balance} balance is wrong; correct amount: {actual_balance}",
            "I challenge the incorrect {reported_balance}; true balance is {actual_balance}",
        ],

        # DATE DISPUTE TEMPLATES (35 variations)
        "date_dispute": [
            "The reported {date_type} of {reported_date} is incorrect; the actual date is {actual_date}",
            "I dispute the {date_type} shown as {reported_date}; it should be {actual_date}",
            "The {date_type} of {reported_date} is inaccurate and should reflect {actual_date}",
            "I challenge the {date_type} ({reported_date}); correct date is {actual_date}",
            "The stated {date_type} of {reported_date} is wrong; it should be {actual_date}",
            "I dispute that the {date_type} is {reported_date}; the accurate date is {actual_date}",
            "The {date_type} showing {reported_date} is erroneous; should show {actual_date}",
            "I contest the {date_type} of {reported_date} as incorrect; true date is {actual_date}",
            "The reported {date_type} ({reported_date}) does not match the correct date of {actual_date}",
            "I dispute the {date_type}: {reported_date}; records indicate {actual_date}",
            "The {date_type} is erroneously reported as {reported_date}; it should be {actual_date}",
            "I challenge the stated {date_type} of {reported_date} which should read {actual_date}",
            "The incorrect {date_type} of {reported_date} should be corrected to {actual_date}",
            "I contest the {date_type} ({reported_date}); accurate date is {actual_date}",
            "The {date_type} shown as {reported_date} is disputed; correct date: {actual_date}",
            "I challenge the inaccurate {date_type} of {reported_date}; should be {actual_date}",
            "The erroneous {date_type} of {reported_date} must be corrected to {actual_date}",
            "I dispute the reported {date_type} of {reported_date} as inaccurate; actual: {actual_date}",
            "The false {date_type} of {reported_date} should reflect the true date of {actual_date}",
            "I contest that the {date_type} is {reported_date}; correct date is {actual_date}",
            "The stated {date_type} ({reported_date}) is wrong and should be {actual_date}",
            "I challenge the {date_type} entry of {reported_date}; accurate date is {actual_date}",
            "The {date_type} figure of {reported_date} is incorrect; it should read {actual_date}",
            "I dispute the inaccurate {date_type} of {reported_date}; true date is {actual_date}",
            "The reported {date_type} of {reported_date} should be corrected to {actual_date}",
            "I contest the erroneous {date_type} of {reported_date}; actual date: {actual_date}",
            "The {date_type} incorrectly shows {reported_date} instead of {actual_date}",
            "I dispute the {date_type} as reported ({reported_date}); it should state {actual_date}",
            "The false {date_type} of {reported_date} must be changed to {actual_date}",
            "I challenge that the {date_type} reads {reported_date}; correct date is {actual_date}",
            "The {date_type} of {reported_date} is disputed as incorrect; should be {actual_date}",
            "I contest the stated {date_type} of {reported_date}; the accurate date is {actual_date}",
            "The erroneous {date_type} ({reported_date}) should reflect {actual_date}",
            "I dispute this {date_type}: reported {reported_date}, actual {actual_date}",
            "The {date_type} ({reported_date}) is wrong; correct date: {actual_date}",
        ],

        # STATUS DISPUTE TEMPLATES (35 variations)
        "status_dispute": [
            "The account status is incorrectly reported as {reported_status}; it should be {actual_status}",
            "I dispute the status showing {reported_status}; the correct status is {actual_status}",
            "The status of {reported_status} is inaccurate and should reflect {actual_status}",
            "I challenge the reported status ({reported_status}); correct status is {actual_status}",
            "The stated status of {reported_status} is wrong; it should be {actual_status}",
            "I dispute that the status is {reported_status}; the accurate status is {actual_status}",
            "The status showing {reported_status} is erroneous; should show {actual_status}",
            "I contest the status of {reported_status} as incorrect; true status is {actual_status}",
            "The reported status ({reported_status}) does not match the correct status of {actual_status}",
            "I dispute the status: {reported_status}; records indicate {actual_status}",
            "The status is erroneously reported as {reported_status}; it should be {actual_status}",
            "I challenge the stated status of {reported_status} which should read {actual_status}",
            "The incorrect status of {reported_status} should be corrected to {actual_status}",
            "I contest the status ({reported_status}); accurate status is {actual_status}",
            "The status shown as {reported_status} is disputed; correct status: {actual_status}",
            "I challenge the inaccurate status of {reported_status}; should be {actual_status}",
            "The erroneous status of {reported_status} must be corrected to {actual_status}",
            "I dispute the reported status of {reported_status} as inaccurate; actual: {actual_status}",
            "The false status of {reported_status} should reflect the true status of {actual_status}",
            "I contest that the status is {reported_status}; correct status is {actual_status}",
            "The stated status ({reported_status}) is wrong and should be {actual_status}",
            "I challenge the status entry of {reported_status}; accurate status is {actual_status}",
            "The status designation of {reported_status} is incorrect; it should read {actual_status}",
            "I dispute the inaccurate status of {reported_status}; true status is {actual_status}",
            "The reported status of {reported_status} should be corrected to {actual_status}",
            "I contest the erroneous status of {reported_status}; actual status: {actual_status}",
            "The status incorrectly shows {reported_status} instead of {actual_status}",
            "I dispute the status as reported ({reported_status}); it should state {actual_status}",
            "The false status of {reported_status} must be changed to {actual_status}",
            "I challenge that the status reads {reported_status}; correct status is {actual_status}",
            "The status of {reported_status} is disputed as incorrect; should be {actual_status}",
            "I contest the stated status of {reported_status}; the accurate status is {actual_status}",
            "The erroneous status ({reported_status}) should reflect {actual_status}",
            "I dispute this status: reported {reported_status}, actual {actual_status}",
            "The status ({reported_status}) is wrong; correct status: {actual_status}",
        ],

        # FCRA VIOLATION TEMPLATES (40 variations)
        "fcra_violation": [
            "This reporting violates {statute_section} which requires {requirement}",
            "The conduct described violates {statute_section} by failing to {requirement}",
            "This constitutes a violation of {statute_section} regarding {requirement}",
            "You have violated {statute_section} which mandates {requirement}",
            "This is a clear violation of {statute_section}: {requirement}",
            "The reporting violates {statute_section} by not ensuring {requirement}",
            "This conduct breaches {statute_section} requiring {requirement}",
            "You are in violation of {statute_section} which states {requirement}",
            "This represents a violation of {statute_section} concerning {requirement}",
            "The failure to {requirement} violates {statute_section}",
            "This constitutes non-compliance with {statute_section}: {requirement}",
            "You have failed to comply with {statute_section} requiring {requirement}",
            "This is a breach of {statute_section} mandating {requirement}",
            "The conduct violates the requirements of {statute_section}: {requirement}",
            "This reporting fails to comply with {statute_section} regarding {requirement}",
            "You are not in compliance with {statute_section} which requires {requirement}",
            "This represents non-compliance with {statute_section}: {requirement}",
            "The failure violates {statute_section} by not providing {requirement}",
            "This constitutes a breach of {statute_section} requiring {requirement}",
            "You have breached {statute_section} which mandates {requirement}",
            "This is a failure to comply with {statute_section}: {requirement}",
            "The reporting fails to meet {statute_section} requirements: {requirement}",
            "This violates the mandate of {statute_section} concerning {requirement}",
            "You are violating {statute_section} by failing to ensure {requirement}",
            "This represents a failure to comply with {statute_section}: {requirement}",
            "The conduct is in violation of {statute_section} requiring {requirement}",
            "This fails to comply with the requirements of {statute_section}: {requirement}",
            "You have failed to meet {statute_section} standards: {requirement}",
            "This constitutes a failure under {statute_section} regarding {requirement}",
            "The reporting is non-compliant with {statute_section}: {requirement}",
            "This is in violation of {statute_section} mandating {requirement}",
            "You are in breach of {statute_section} which requires {requirement}",
            "This represents a violation under {statute_section}: {requirement}",
            "The failure to ensure {requirement} breaches {statute_section}",
            "This is a clear breach of {statute_section} requirements: {requirement}",
            "You have not complied with {statute_section} concerning {requirement}",
            "This constitutes non-adherence to {statute_section}: {requirement}",
            "The conduct fails to meet {statute_section} requirements for {requirement}",
            "This violates {statute_section}'s mandate regarding {requirement}",
            "You are failing to comply with {statute_section}: {requirement}",
        ],

        # DEMAND TEMPLATES (30 variations)
        "demand_action": [
            "I demand that you {action} within {timeframe} days",
            "You are required to {action} no later than {timeframe} days from receipt",
            "I require that you {action} within the {timeframe}-day statutory period",
            "You must {action} within {timeframe} days of this notice",
            "I demand immediate {action} within {timeframe} days",
            "You are obligated to {action} within {timeframe} days",
            "I require {action} within {timeframe} days as mandated by law",
            "You must {action} no later than {timeframe} days from today",
            "I demand that you {action} within the statutory {timeframe}-day period",
            "You are legally required to {action} within {timeframe} days",
            "I require immediate {action} within {timeframe} days of receipt",
            "You must {action} within {timeframe} days pursuant to statute",
            "I demand {action} within the {timeframe}-day legal timeframe",
            "You are mandated to {action} within {timeframe} days",
            "I require that you {action} within {timeframe} days of this letter",
            "You must {action} within the legally required {timeframe} days",
            "I demand {action} no later than {timeframe} days hence",
            "You are required by law to {action} within {timeframe} days",
            "I require {action} within the next {timeframe} days",
            "You must {action} within {timeframe} days as required",
            "I demand immediate compliance: {action} within {timeframe} days",
            "You are obligated by statute to {action} within {timeframe} days",
            "I require that you {action} per the {timeframe}-day requirement",
            "You must {action} within {timeframe} days from this date",
            "I demand {action} within {timeframe} days of receipt of this notice",
            "You are required to {action} within the next {timeframe} days",
            "I require immediate {action} per the {timeframe}-day statute",
            "You must {action} within {timeframe} days in compliance with law",
            "I demand that you {action} within {timeframe} calendar days",
            "You are legally obligated to {action} within {timeframe} days",
        ],
    },

    "civil": {
        # ACCOUNT DISPUTE TEMPLATES (50 variations)
        "account_dispute": [
            "I found a problem with the {creditor_name} account ({account_number}) - it shows as {dispute_reason}",
            "The account from {creditor_name} (number {account_number}) isn't right because {dispute_reason}",
            "I noticed the {creditor_name} account {account_number} is {dispute_reason}",
            "There's an issue with account {account_number} from {creditor_name}: {dispute_reason}",
            "The {creditor_name} account ({account_number}) appears to be {dispute_reason}",
            "I'm disputing {creditor_name} account {account_number} because it's {dispute_reason}",
            "Account {account_number} with {creditor_name} shows {dispute_reason}",
            "The entry for {creditor_name} (account {account_number}) is {dispute_reason}",
            "I found that {creditor_name} account {account_number} is {dispute_reason}",
            "There's a problem with the {creditor_name} account numbered {account_number}: {dispute_reason}",
            "The {creditor_name} account ({account_number}) is showing as {dispute_reason}",
            "I need help with {creditor_name} account {account_number} which is {dispute_reason}",
            "Account {account_number} from {creditor_name} appears {dispute_reason}",
            "The entry for account {account_number} ({creditor_name}) is {dispute_reason}",
            "I'm concerned about {creditor_name} account {account_number}: {dispute_reason}",
            "The {creditor_name} account with number {account_number} shows {dispute_reason}",
            "I noticed a problem with account {account_number} from {creditor_name}: {dispute_reason}",
            "There's an error with {creditor_name} ({account_number}): {dispute_reason}",
            "The account {account_number} under {creditor_name} is {dispute_reason}",
            "I found an issue with {creditor_name}'s account {account_number}: {dispute_reason}",
            "Account {account_number} listed under {creditor_name} is {dispute_reason}",
            "The {creditor_name} entry (account {account_number}) appears {dispute_reason}",
            "I'm writing about {creditor_name} account {account_number} which shows {dispute_reason}",
            "There's something wrong with account {account_number} from {creditor_name}: {dispute_reason}",
            "The {creditor_name} account numbered {account_number} is {dispute_reason}",
            "I have a concern about {creditor_name} ({account_number}): {dispute_reason}",
            "Account {account_number} with the creditor {creditor_name} is {dispute_reason}",
            "The entry for {creditor_name}'s account {account_number} is {dispute_reason}",
            "I noticed that {creditor_name} account {account_number} shows {dispute_reason}",
            "There's an issue with the {creditor_name} account ({account_number}): {dispute_reason}",
            "The {creditor_name} account {account_number} appears to be {dispute_reason}",
            "I need to dispute {creditor_name} account {account_number} because it's {dispute_reason}",
            "Account {account_number} from the creditor {creditor_name} shows {dispute_reason}",
            "The entry under {creditor_name} (account {account_number}) is {dispute_reason}",
            "I found a mistake with {creditor_name} account {account_number}: {dispute_reason}",
            "There's a concern with the {creditor_name} account {account_number}: {dispute_reason}",
            "The {creditor_name} account (number {account_number}) is {dispute_reason}",
            "I'm having an issue with {creditor_name} ({account_number}): {dispute_reason}",
            "Account {account_number} listed by {creditor_name} is {dispute_reason}",
            "The entry for {creditor_name} account number {account_number} is {dispute_reason}",
            "I noticed something wrong with {creditor_name} account {account_number}: {dispute_reason}",
            "There's a problem with account {account_number} listed under {creditor_name}: {dispute_reason}",
            "The {creditor_name} account with {account_number} shows as {dispute_reason}",
            "I have a question about {creditor_name} ({account_number}): {dispute_reason}",
            "Account {account_number} attributed to {creditor_name} is {dispute_reason}",
            "The entry for {creditor_name}, account {account_number}, is {dispute_reason}",
            "I found that the {creditor_name} account {account_number} is {dispute_reason}",
            "There's an error in {creditor_name} account {account_number}: {dispute_reason}",
            "The {creditor_name} entry for account {account_number} shows {dispute_reason}",
            "I need help disputing {creditor_name} account {account_number}: {dispute_reason}",
        ],

        # BALANCE DISPUTE TEMPLATES (35 variations)
        "balance_dispute": [
            "The balance shows {reported_balance} but it should be {actual_balance}",
            "I noticed the balance is {reported_balance} when it should be {actual_balance}",
            "The balance of {reported_balance} isn't correct - it should be {actual_balance}",
            "There's a balance error: it shows {reported_balance} but should be {actual_balance}",
            "The balance is showing {reported_balance} instead of the correct amount {actual_balance}",
            "I found that the balance is wrong: {reported_balance} vs {actual_balance}",
            "The balance of {reported_balance} doesn't match my records of {actual_balance}",
            "There's a mistake with the balance: {reported_balance} should be {actual_balance}",
            "The reported balance of {reported_balance} is off - correct amount is {actual_balance}",
            "I noticed the balance ({reported_balance}) should actually be {actual_balance}",
            "The balance shows {reported_balance} but my records show {actual_balance}",
            "There's a discrepancy: balance is {reported_balance} but should be {actual_balance}",
            "The balance amount of {reported_balance} isn't right - it's {actual_balance}",
            "I found a balance error: {reported_balance} instead of {actual_balance}",
            "The balance is incorrectly listed as {reported_balance}; it should be {actual_balance}",
            "There's a problem with the balance: showing {reported_balance}, should be {actual_balance}",
            "The balance of {reported_balance} needs to be corrected to {actual_balance}",
            "I noticed the wrong balance: {reported_balance} vs the correct {actual_balance}",
            "The balance shows {reported_balance} but the actual amount is {actual_balance}",
            "There's an error in the balance: {reported_balance} should read {actual_balance}",
            "The balance ({reported_balance}) is inaccurate - correct balance is {actual_balance}",
            "I found that the balance of {reported_balance} should be {actual_balance}",
            "The balance is showing as {reported_balance} but it's really {actual_balance}",
            "There's a balance issue: reported {reported_balance}, actual {actual_balance}",
            "The balance of {reported_balance} doesn't reflect the true amount of {actual_balance}",
            "I noticed a balance discrepancy: {reported_balance} vs {actual_balance}",
            "The balance shows {reported_balance} which is wrong - it's {actual_balance}",
            "There's an incorrect balance: {reported_balance} should be {actual_balance}",
            "The balance is listed as {reported_balance} but correct amount is {actual_balance}",
            "I found a balance problem: {reported_balance} instead of {actual_balance}",
            "The balance ({reported_balance}) needs correction to {actual_balance}",
            "There's a mistake: balance is {reported_balance} but should be {actual_balance}",
            "The balance of {reported_balance} is wrong; the right amount is {actual_balance}",
            "I noticed the balance is off: {reported_balance} should be {actual_balance}",
            "The balance shows {reported_balance} but I believe it's {actual_balance}",
        ],

        # DATE DISPUTE TEMPLATES (30 variations)
        "date_dispute": [
            "The {date_type} shows {reported_date} but it should be {actual_date}",
            "I noticed the {date_type} is {reported_date} when it should be {actual_date}",
            "The {date_type} of {reported_date} isn't correct - it should be {actual_date}",
            "There's a date error: the {date_type} shows {reported_date} but should be {actual_date}",
            "The {date_type} is showing {reported_date} instead of the correct date {actual_date}",
            "I found that the {date_type} is wrong: {reported_date} vs {actual_date}",
            "The {date_type} of {reported_date} doesn't match my records of {actual_date}",
            "There's a mistake with the {date_type}: {reported_date} should be {actual_date}",
            "The reported {date_type} of {reported_date} is off - correct date is {actual_date}",
            "I noticed the {date_type} ({reported_date}) should actually be {actual_date}",
            "The {date_type} shows {reported_date} but my records show {actual_date}",
            "There's a discrepancy: {date_type} is {reported_date} but should be {actual_date}",
            "The {date_type} of {reported_date} isn't right - it's {actual_date}",
            "I found a date error: {date_type} is {reported_date} instead of {actual_date}",
            "The {date_type} is incorrectly listed as {reported_date}; it should be {actual_date}",
            "There's a problem with the {date_type}: showing {reported_date}, should be {actual_date}",
            "The {date_type} of {reported_date} needs to be corrected to {actual_date}",
            "I noticed the wrong {date_type}: {reported_date} vs the correct {actual_date}",
            "The {date_type} shows {reported_date} but the actual date is {actual_date}",
            "There's an error in the {date_type}: {reported_date} should read {actual_date}",
            "The {date_type} ({reported_date}) is inaccurate - correct date is {actual_date}",
            "I found that the {date_type} of {reported_date} should be {actual_date}",
            "The {date_type} is showing as {reported_date} but it's really {actual_date}",
            "There's a date issue: {date_type} reported {reported_date}, actual {actual_date}",
            "The {date_type} of {reported_date} doesn't reflect the true date of {actual_date}",
            "I noticed a {date_type} discrepancy: {reported_date} vs {actual_date}",
            "The {date_type} shows {reported_date} which is wrong - it's {actual_date}",
            "There's an incorrect {date_type}: {reported_date} should be {actual_date}",
            "The {date_type} is listed as {reported_date} but correct date is {actual_date}",
            "I found a {date_type} problem: {reported_date} instead of {actual_date}",
        ],

        # STATUS DISPUTE TEMPLATES (30 variations)
        "status_dispute": [
            "The status shows {reported_status} but it should be {actual_status}",
            "I noticed the status is {reported_status} when it should be {actual_status}",
            "The status of {reported_status} isn't correct - it should be {actual_status}",
            "There's a status error: it shows {reported_status} but should be {actual_status}",
            "The status is showing {reported_status} instead of the correct status {actual_status}",
            "I found that the status is wrong: {reported_status} vs {actual_status}",
            "The status of {reported_status} doesn't match my records of {actual_status}",
            "There's a mistake with the status: {reported_status} should be {actual_status}",
            "The reported status of {reported_status} is off - correct status is {actual_status}",
            "I noticed the status ({reported_status}) should actually be {actual_status}",
            "The status shows {reported_status} but my records show {actual_status}",
            "There's a discrepancy: status is {reported_status} but should be {actual_status}",
            "The status of {reported_status} isn't right - it's {actual_status}",
            "I found a status error: {reported_status} instead of {actual_status}",
            "The status is incorrectly listed as {reported_status}; it should be {actual_status}",
            "There's a problem with the status: showing {reported_status}, should be {actual_status}",
            "The status of {reported_status} needs to be corrected to {actual_status}",
            "I noticed the wrong status: {reported_status} vs the correct {actual_status}",
            "The status shows {reported_status} but the actual status is {actual_status}",
            "There's an error in the status: {reported_status} should read {actual_status}",
            "The status ({reported_status}) is inaccurate - correct status is {actual_status}",
            "I found that the status of {reported_status} should be {actual_status}",
            "The status is showing as {reported_status} but it's really {actual_status}",
            "There's a status issue: reported {reported_status}, actual {actual_status}",
            "The status of {reported_status} doesn't reflect the true status of {actual_status}",
            "I noticed a status discrepancy: {reported_status} vs {actual_status}",
            "The status shows {reported_status} which is wrong - it's {actual_status}",
            "There's an incorrect status: {reported_status} should be {actual_status}",
            "The status is listed as {reported_status} but correct status is {actual_status}",
            "I found a status problem: {reported_status} instead of {actual_status}",
        ],

        # REQUEST TEMPLATES (25 variations)
        "request_action": [
            "I'm hoping you can {action} for me",
            "Could you please {action}?",
            "I would appreciate if you could {action}",
            "Would you be able to {action}?",
            "I'm asking if you could {action}",
            "Could you help me by {action}?",
            "I'd like to request that you {action}",
            "Would it be possible to {action}?",
            "I'm requesting that you {action}",
            "Could you please help with {action}?",
            "I would be grateful if you could {action}",
            "Would you mind {action}?",
            "I'm hoping you might be able to {action}",
            "Could you assist me by {action}?",
            "I'd appreciate it if you would {action}",
            "Would you be willing to {action}?",
            "I'm asking for your help to {action}",
            "Could you please look into {action}?",
            "I would like you to {action}",
            "Would you consider {action}?",
            "I'm reaching out to ask you to {action}",
            "Could you take care of {action}?",
            "I'd be thankful if you could {action}",
            "Would you help me with {action}?",
            "I'm writing to ask if you could {action}",
        ],

        # EXPLANATION TEMPLATES (25 variations)
        "explanation": [
            "This is causing me problems because {reason}",
            "The issue is that {reason}",
            "I'm concerned because {reason}",
            "This matters to me because {reason}",
            "The problem is {reason}",
            "I need this fixed because {reason}",
            "This affects me because {reason}",
            "I'm worried because {reason}",
            "This is important because {reason}",
            "The concern is that {reason}",
            "I need help with this because {reason}",
            "This is frustrating because {reason}",
            "I'm reaching out because {reason}",
            "This needs attention because {reason}",
            "I'm writing because {reason}",
            "This is a problem because {reason}",
            "I need this resolved because {reason}",
            "This concerns me because {reason}",
            "I'm asking for help because {reason}",
            "This is bothering me because {reason}",
            "I need your help because {reason}",
            "This is urgent because {reason}",
            "I'm contacting you because {reason}",
            "This requires attention because {reason}",
            "I'm disputing this because {reason}",
        ],
    },
}
