"""
Transition Pools - 50+ variations per category for smooth section transitions.
Used between paragraphs and sections for natural flow.
"""
from typing import Dict, List

TRANSITION_POOLS: Dict[str, List[str]] = {
    # SECTION TRANSITIONS (50+ each)
    "section_to_section": [
        "Moving on to the next issue,",
        "Additionally,",
        "Furthermore,",
        "In addition to the above,",
        "Moreover,",
        "Beyond this,",
        "Also of concern,",
        "Continuing with my dispute,",
        "Another matter requiring attention is",
        "I also need to address",
        "The next item I am disputing is",
        "Equally important,",
        "I must also bring to your attention",
        "Similarly,",
        "In the same vein,",
        "Along these lines,",
        "Building on the above,",
        "As a related matter,",
        "Connected to this,",
        "On a related note,",
        "Additionally requiring investigation,",
        "Furthermore requiring your attention,",
        "Also in need of correction,",
        "The following item also requires review,",
        "I am also disputing",
        "Another disputed entry is",
        "The next disputed item is",
        "Also appearing incorrectly,",
        "In addition to the foregoing,",
        "Adding to my concerns,",
        "Another point of dispute is",
        "Beyond what I have stated,",
        "Supplementing my dispute,",
        "Further to the above,",
        "As an additional matter,",
        "Turning to another issue,",
        "The next matter concerns",
        "I further dispute",
        "Additionally, I contest",
        "Moreover, I challenge",
        "Another issue requiring resolution is",
        "Continuing with disputed items,",
        "Further items of concern include",
        "Additional disputed entries include",
        "My dispute also encompasses",
        "I am additionally disputing",
        "The following also requires investigation,",
        "Further requiring your attention,",
        "As another disputed item,",
        "Moving to the next disputed entry,",
    ],

    # INTRO TO VIOLATIONS (50+ variations)
    "intro_to_violations": [
        "The specific items I am disputing are as follows:",
        "I have identified the following errors on my credit report:",
        "The inaccuracies I am disputing include:",
        "My dispute encompasses the following items:",
        "The following information is inaccurate and requires correction:",
        "I am formally disputing the following entries:",
        "The erroneous items requiring investigation are:",
        "Below are the specific items requiring your attention:",
        "The disputed entries are detailed below:",
        "I contest the following reported information:",
        "The inaccurate information includes:",
        "My dispute covers the following items:",
        "The errors I have identified are:",
        "I am challenging the following entries:",
        "The items requiring correction include:",
        "Specifically, I dispute:",
        "The following entries are incorrect:",
        "Below you will find the disputed items:",
        "I have found the following errors:",
        "The inaccurate entries are:",
        "My concerns include the following items:",
        "The disputed information is as follows:",
        "I am contesting the following:",
        "The errors requiring investigation are:",
        "Specifically, the following items are incorrect:",
        "I dispute the following reported entries:",
        "The inaccuracies I have found include:",
        "Below are the errors in my credit report:",
        "The following items are being disputed:",
        "I have identified these errors:",
        "My dispute addresses the following:",
        "The incorrect information includes:",
        "I am formally challenging:",
        "The following requires reinvestigation:",
        "Below are my disputed items:",
        "The errors in my report include:",
        "I contest the following items:",
        "The disputed entries include:",
        "Specifically, I am disputing:",
        "The following information is wrong:",
        "My dispute concerns:",
        "The items I dispute are:",
        "Below are the inaccuracies:",
        "I am disputing these entries:",
        "The errors are as follows:",
        "My concerns are detailed below:",
        "The following items are disputed:",
        "I have found these errors:",
        "The incorrect entries are:",
        "Specifically, I challenge:",
    ],

    # VIOLATIONS TO DEMANDS (50+ variations)
    "violations_to_demands": [
        "Given these violations, I demand that you",
        "Based on the above, I require",
        "In light of these errors, I request",
        "Considering these inaccuracies, I demand",
        "As a result of these violations, I require",
        "Due to these errors, I am requesting",
        "Because of these inaccuracies, I demand",
        "In view of the above, I require",
        "Given what I have documented, I request",
        "Based on these findings, I demand",
        "Consequently, I require",
        "Therefore, I am requesting",
        "As such, I demand",
        "For these reasons, I require",
        "Accordingly, I request",
        "Thus, I demand that you",
        "Hence, I require",
        "As a consequence, I request",
        "In response to these issues, I demand",
        "Following from this, I require",
        "Given the foregoing, I request",
        "Based on my findings, I demand",
        "In consideration of these errors, I require",
        "Owing to these violations, I request",
        "As a result, I demand",
        "Because of the above, I require",
        "Due to these issues, I request",
        "In light of the foregoing, I demand",
        "Considering everything stated, I require",
        "Given these circumstances, I request",
        "Based on the documented errors, I demand",
        "In view of these violations, I require",
        "As a result of my findings, I request",
        "Due to the inaccuracies described, I demand",
        "Because of what I have documented, I require",
        "In response to these errors, I request",
        "Following my investigation, I demand",
        "Given the errors I have identified, I require",
        "Based on everything above, I request",
        "In consideration of the foregoing, I demand",
        "Owing to the issues documented, I require",
        "As a consequence of these errors, I request",
        "Because of the violations detailed, I demand",
        "Due to the inaccuracies above, I require",
        "In light of my findings, I request",
        "Considering the documented errors, I demand",
        "Given the foregoing issues, I require",
        "Based on the violations cited, I request",
        "In view of everything stated, I demand",
        "As a result of the above, I require",
    ],

    # DEMANDS TO CLOSURE (50+ variations)
    "demands_to_closure": [
        "I expect your prompt attention to this matter.",
        "I await your timely response.",
        "I look forward to resolution of this dispute.",
        "Your prompt action is expected.",
        "I anticipate your swift response.",
        "I expect compliance within the statutory period.",
        "I await your investigation results.",
        "Your timely attention is required.",
        "I expect a prompt resolution.",
        "I look forward to hearing from you.",
        "Your response is required within 30 days.",
        "I await your compliance with this request.",
        "I expect your full cooperation.",
        "Your prompt response is anticipated.",
        "I look forward to your investigation.",
        "I await resolution of these issues.",
        "Your timely compliance is expected.",
        "I expect your attention to these matters.",
        "I anticipate your prompt action.",
        "Your response within the required timeframe is expected.",
        "I await your findings.",
        "I expect this matter to be resolved promptly.",
        "Your swift attention is anticipated.",
        "I look forward to a favorable resolution.",
        "I await your written response.",
        "I expect compliance with applicable law.",
        "Your prompt attention is required.",
        "I anticipate resolution of this dispute.",
        "I look forward to correction of these errors.",
        "I await your investigation and response.",
        "I expect your timely action.",
        "Your compliance is required.",
        "I anticipate your prompt response.",
        "I look forward to your cooperation.",
        "I await correction of these items.",
        "I expect a complete investigation.",
        "Your response is anticipated.",
        "I look forward to hearing your findings.",
        "I await your attention to this matter.",
        "I expect thorough investigation.",
        "Your prompt compliance is required.",
        "I anticipate a positive outcome.",
        "I look forward to resolution.",
        "I await your prompt action.",
        "I expect your investigation.",
        "Your timely response is required.",
        "I anticipate correction of errors.",
        "I look forward to your response.",
        "I await compliance with my demands.",
        "I expect prompt attention.",
    ],

    # BETWEEN VIOLATION ITEMS (30+ variations)
    "between_items": [
        "Additionally,",
        "Furthermore,",
        "Moreover,",
        "Also,",
        "In addition,",
        "Similarly,",
        "Likewise,",
        "Next,",
        "Also disputed,",
        "Another item,",
        "The following item,",
        "Continuing,",
        "Further,",
        "As well,",
        "Additionally disputed,",
        "Also requiring attention,",
        "Another entry,",
        "The next item,",
        "Further disputed,",
        "Also incorrect,",
        "Another error,",
        "Also inaccurate,",
        "Additionally incorrect,",
        "Further requiring review,",
        "Also in error,",
        "Another disputed entry,",
        "The next disputed item,",
        "Also needing correction,",
        "Another matter,",
        "Also of concern,",
    ],

    # CIVIL TRANSITIONS (50+ variations for civil letters)
    "civil_transitions": [
        "I also wanted to mention",
        "Another thing I noticed",
        "Also,",
        "In addition to that,",
        "I also found",
        "Another issue I saw",
        "On top of that,",
        "There's also",
        "I also need to point out",
        "Additionally,",
        "Another problem I found",
        "I also noticed",
        "Plus,",
        "And also,",
        "There's another thing",
        "I should also mention",
        "Another concern is",
        "Also on my report,",
        "I also discovered",
        "Another item I found",
        "Besides that,",
        "I also came across",
        "Another error I noticed",
        "Also wrong on my report,",
        "I also spotted",
        "Another mistake I found",
        "Along with that,",
        "I also saw",
        "Another thing that's wrong",
        "Also appearing incorrectly,",
        "I also need help with",
        "Another issue is",
        "Additionally incorrect,",
        "I also want to dispute",
        "Another entry that's wrong",
        "Also needing correction,",
        "I also have concerns about",
        "Another problem is",
        "And another thing,",
        "I also found an error with",
        "Another inaccurate item",
        "Also not right,",
        "I also noticed problems with",
        "Another mistake on my report",
        "Additionally problematic,",
        "I also need to address",
        "Another thing that needs fixing",
        "Also in error,",
        "I also want to point out",
        "Another concern I have",
    ],
}
